Repository ToogaInc/ToogaBooga, pull requests merged in 2022-07, with the labels that each got.

#195 fix(logkey): edit slash cmd options
  src/commands/logging/LogKey.ts
Labels: bug, minor

#198 feat(afk-check): dps reacts
  src/constants/EmojiConstants.ts
  src/constants/dungeons/MappedAfkCheckReactions.ts
Labels: enhancement, minor

#201 fix(c:afkcheck): change min val to 0
  src/commands/config/ConfigAfkCheck.ts
Labels: it-bug, c-raid, c-config

#172 refactor(logging): adding tons of logging for errors and rate-limits
  src/Bot.ts
  src/commands/config/ConfigAfkCheck.ts
  src/events/ErrorEvent.ts
  src/events/InteractionEvent.ts
  src/events/RatelimitEvent.ts
  src/events/index.ts
  src/instances/HeadcountInstance.ts
  src/instances/RaidInstance.ts
  src/managers/PunishmentManager.ts
  src/managers/QuotaManager.ts
  src/utilities/collectors/AdvancedCollector.ts
  src/utilities/fetch-get-request/GlobalFgrUtilities.ts
  src/utilities/fetch-get-request/GuildFgrUtilities.ts
Labels: it-enhancement, c-error handling

#203 Get guilds from cache instead of requesting it from Discord & removed send announcement command
  src/Bot.ts
  src/commands/index.ts
  src/commands/owner/SendAnnouncement.ts
  src/instances/HeadcountInstance.ts
  src/instances/RaidInstance.ts
  src/managers/PunishmentManager.ts
  src/managers/QuotaManager.ts
  src/utilities/fetch-get-request/GlobalFgrUtilities.ts
Labels: it-bug, it-enhancement, c-error handling

#205 [1.2.0] Verification
  CONTRIBUTING.md
  LICENSE
  README.md
  assets/banner.png
  docs/contributing.md
  docs/docs-guide.md
  docs/setup.md
  docs/some-notes.md
  package-lock.json
  package.json
  src/Bot.ts
  src/commands/config/ConfigAfkCheck.ts
  src/commands/config/ConfigSections.ts
  src/commands/config/ConfigVerification.ts
  src/commands/index.ts
  src/commands/staff/CheckManualVerifyApp.ts
  src/definitions/VerificationInterfaces.ts
  src/events/GuildMemberRemoveEvent.ts
  src/events/InteractionEvent.ts
  src/events/MessageEvent.ts
  src/events/index.ts
  src/managers/InteractivityManager.ts
  src/managers/MongoManager.ts
  src/managers/PunishmentManager.ts
  src/managers/QuotaManager.ts
  src/managers/VerifyManager.ts
  src/utilities/collectors/AdvancedCollector.ts
  tsconfig.json
Labels: it-enhancement, c-verification

#211 [1.2.1] Verification hotfix.
  package.json
  src/commands/config/ConfigChannels.ts
  src/commands/config/ConfigRoles.ts
  src/commands/staff/EditName.ts
  src/commands/staff/ManualVerifyMain.ts
  src/commands/staff/ManualVerifySection.ts
  src/commands/staff/RemoveName.ts
  src/managers/UserManager.ts
  src/managers/VerifyManager.ts
  src/private-api/PrivateApiDefinitions.ts
  src/utilities/MiscUtilities.ts
Labels: c-verification

#213 Fixed a bug caused by users having a document in db, but no names in it
  src/managers/VerifyManager.ts
Labels: it-bug, c-verification
